-keep class com.javis.os.data.remote.dto.** { *; }
-keep class com.javis.os.data.local.entities.** { *; }
-keepattributes Signature
-keepattributes *Annotation*
-dontwarn okhttp3.**
-dontwarn retrofit2.**
